project_name: tlsg-cli
builds:
  - id: tlsg-cli
    main: ./main.go
    binary: tlsg-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
